#:schema https://json.schemastore.org/wrangler.toml
name = "titan"
compatibility_date = "2026-06-25"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "titansportgear-blog"
database_id = "ab3c18f1-c794-4cf0-a024-06cd41af2946"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "titansportgear-assets"